//try{
  //  console.log("hello world")

//}
//catch(err){
  //  console.log('err.message ')

//}
//let x = 5;
//try {
  //x = y + 1;   // y cannot be used (referenced)
//}
//catch(err){
    //console.log(err.name);
    //console.log(err.message);
//}